# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Update private key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_SSH_KEY }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[tests]
          # Install saci-database
          ACTIVE_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          git clone git@github.com:senpai-on-fire/saci-database.git
          (cd saci-database && git checkout $ACTIVE_BRANCH && pip install .)

      - name: Pytest
        run: |
          pytest ./tests/

  container:
    name: Build and publish containers
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Rewrite git ssh urls to https
        run: |
          sed -i 's,git@github.com:,https://github.com/:,g' .gitmodules

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ghcr.io/senpai-on-fire/saci/saci
          file: Dockerfile