# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Artifact Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Load private key
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.PRIVATE_SSH_KEY }}'
      - name: Install library repository
        run: |
          ACTIVE_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          git clone git@github.com:senpai-on-fire/saci-database.git
          (cd saci-database && git checkout $ACTIVE_BRANCH && pip install .)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[tests]

      - name: Pytest
        run: |
          pytest ./tests/
